$(document).ready(function(){
    //var json = {"data":{"title":"Data","typeForm":"DATA","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"text","placeholder":"Insira uma data","fieldHtmlClass":"dataField"}},"calendario":{"title":"Calendario","format":"date","typeForm":"CALENDARIO","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"datepicker","format":"dd/mm/yyyy","placeholder":"Selecione uma data","fieldHtmlClass":"calendarForm"}},"selecionar":{"title":"Selecionar","typeForm":"SELECIONAR","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"select","placeholder":"Selecione o valor do campo"},"enum":["Sim","Não"]},"checkbox":{"title":"CheckBox","typeForm":"CHECK-BOX","obrigatorio":true,"type":"array","dicaCampo":"","x-schema-form":{"type":"checkboxes","htmlClass":"checkBoxSchema","fieldHtmlClass":"checkBoxSchemaInput"},"items":{"type":"string","enum":["Sim","Não"]}},"radiobox":{"title":"RadioBox","typeForm":"RADIO","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"radios","htmlClass":"radioSchema"},"enum":["Sim","Não"]}};

    var json = {"texto":{"title":"TEXTO","typeForm":"TEXTO","obrigatorio":true,"dicaCampo":"","type":"string","x-schema-form":{"type":"text","placeholder":"Insira o valor do campo"}},"texto_longo":{"title":"TEXTO LONGO","typeForm":"TEXTO-LONGO","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"textarea","placeholder":"Insira o valor do campo"}},"numeros":{"title":"NUMEROS","typeForm":"NUMERO","obrigatorio":true,"type":"number","dicaCampo":"","x-schema-form":{"type":"number","placeholder":"Insira o valor do campo"}},"data":{"title":"DATA","typeForm":"DATA","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"text","placeholder":"Insira uma data","fieldHtmlClass":"dataField"}},"calendario":{"title":"CALENDARIO","format":"date","typeForm":"CALENDARIO","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"datepicker","format":"dd/mm/yyyy","placeholder":"Selecione uma data","fieldHtmlClass":"calendarForm"}},"selecionar":{"title":"SELECIONAR","typeForm":"SELECIONAR","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"select","placeholder":"Selecione o valor do campo"},"enum":["OPT1","OPT2"]},"checkbox":{"title":"CHECKBOX","typeForm":"CHECK-BOX","obrigatorio":true,"type":"array","dicaCampo":"","x-schema-form":{"type":"checkboxes","htmlClass":"checkBoxSchema","fieldHtmlClass":"checkBoxSchemaInput"},"items":{"type":"string","enum":["OPT1","OPT2"]}},"radiobox":{"title":"RADIOBOX","typeForm":"RADIO","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"radios","htmlClass":"radioSchema"},"enum":["OPT1","OPT2"]},"email":{"title":"EMAIL","typeForm":"EMAIL","obrigatorio":true,"type":"string","dicaCampo":"","pattern":"^\\S+@\\S+$","description":"Insira um email valido.","x-schema-form":{"type":"text","placeholder":"Insira o valor do campo"}},"telefone":{"title":"TELEFONE","typeForm":"PHONE","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"text","placeholder":"Insira o valor do campo","fieldHtmlClass":"phoneField"}},"senha":{"title":"SENHA","typeForm":"SECRETO","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"password","placeholder":"Insira o valor do campo"}},"anexo1":{"title":"ANEXO1","typeForm":"ANEXO","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"fileUpload","options":{"onReadFn":"showContent"}},"archivo":{"title":"Archivo","type":"string","format":"file","description":"","idImage":""}},"anexo2":{"title":"ANEXO2","typeForm":"ANEXO","obrigatorio":true,"type":"string","dicaCampo":"","x-schema-form":{"type":"fileUpload","options":{"onReadFn":"showContent"}},"archivo":{"title":"Archivo","type":"string","format":"file","description":"","idImage":""}}};

    console.log(json);
    var id = 'myform';
    $("#myform").formMobile(json, id);

});